# Generated by Django 5.1.2 on 2024-11-05 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True,
                                              validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?1?\\d{8,15}$')], verbose_name='Teléfono')),
                ('tipo_contacto', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio'), ('otros', 'Otros')], max_length=10, verbose_name='Tipo de contacto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('recaptcha_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Score reCAPTCHA')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
