# Generated by Django 5.1.3 on 2024-12-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_cliente',
            field=models.BooleanField(default=True),
        ),
    ]
