# Generated by Django 5.1.2 on 2024-11-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=150, unique=True)),
                ('descontinuado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=150, unique=True)),
                ('descontinuado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_temporal_id', models.CharField(help_text='ID único para clientes no registrados', max_length=40, null=True, unique=True)),
                ('pagado', models.BooleanField(default=False, help_text='Indica si el pedido ha sido pagado completamente.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En Preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('completado', models.BooleanField(default=False)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(max_length=100, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.PositiveIntegerField()),
                ('stock_producto', models.PositiveIntegerField()),
                ('descontinuado', models.BooleanField(default=False)),
                ('categorias', models.ManyToManyField(blank=True, to='shop.categoria')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_al_momento', models.PositiveIntegerField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoitem_set', to='shop.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='pedidos', through='shop.ProductoItem', to='shop.producto'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('descripcion_servicio', models.TextField()),
                ('descontinuado', models.BooleanField(default=False)),
                ('precio_servicio', models.PositiveIntegerField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, to='shop.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_servicio', models.PositiveIntegerField(blank=True, help_text='Precio específico acordado para este servicio en la cotización', null=True)),
                ('detalles_cotizacion', models.TextField(blank=True, help_text='Detalles específicos de la cotización si aplica')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_items', to='shop.pedido')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Item',
                'verbose_name_plural': 'Servicio Items',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicios',
            field=models.ManyToManyField(related_name='pedidos', through='shop.ServicioItem', to='shop.servicio'),
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producto')),
            ],
            options={
                'unique_together': {('producto', 'categoria')},
            },
        ),
    ]
