# Generated by Django 5.1.3 on 2024-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_producto_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(through='shop.ProductoCategoria', to='shop.categoria'),
        ),
    ]
