# Generated by Django 5.1.3 on 2024-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_servicio_categorias_serviciocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categorias',
            field=models.ManyToManyField(related_name='servicios', through='shop.ServicioCategoria', to='shop.categoria'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_servicio',
            field=models.PositiveIntegerField(),
        ),
    ]
