# Generated by Django 5.1.3 on 2024-12-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_servicio_categorias_alter_servicio_precio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='codigo_servicio',
            field=models.CharField(max_length=100, null=False, unique=True),
        ),
    ]
