# Generated by Django 5.1.4 on 2024-12-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegionYComunaCL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comuna',
            table='comuna',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
    ]
